# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5c988a1be31d9811e2c03483b4a230698c84ded6689fdb9a2ec29e48d682b5337e76b6cb8d7f8c3c7618f1b3f2176f1a94f28c1ed3c2a263c446a77cc698738
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>

test:
  secret_key_base: 1c37db8d69dcc95dee4e6510bb1e95d6c26a78a70505e6cad6ef11e09ced877938072994c40d201997860b204c71e7438cc02a03d21d02c52b3302ea899c96e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
